list/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import views

# TODO: make server serve images (cvontroller), not djangi url

urlpatterns = [
    url(r'^(?P<share>[a-zA-Z0-9]{20,32})/$', views.share, name='share'),
    url(r'^lists/buy/$', views.buy, name='buy'),
    url(r'^lists/(\d+)/delete/(\d+)/$', views.delete_item, name='delete_item'),
    url(r'^lists/(\d+)/$', views.add_item, name='items'),
    url(r'^lists/add/$', views.add_list, name='add_list'),
    url(r'^lists/$', TemplateView.as_view(template_name='lists.html'), name='lists'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listfully/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^profile/$', TemplateView.as_view(template_name='profile.html'), name='profile'),
    url(r'', include('list.urls')),
    url(r'', include('registration.backends.simple.urls')),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
]

list/models.py
from django.db import models
from django.contrib.auth.models import User as auth_user
from PIL import Image, ExifTags

def item_image_path(instance, filename):
    return ('item_images/' + filename).format(auth_user.id, instance.id)

# TODO: add hash URL to list for non authenthiced users to use.

class List(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(auth_user)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200, blank=True)
    share = models.CharField(max_length=32, unique=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

class Item(models.Model):
    id = models.AutoField(primary_key=True)
    list = models.ForeignKey(List, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=300, blank=True)
    price_range = models.CharField(max_length=20, blank=True)
    url = models.CharField(max_length=500, blank=True)
    image = models.ImageField(upload_to=item_image_path, blank=True)
    thumbnail = models.ImageField(upload_to=item_image_path, blank=True)
    bought = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    location = models.CharField(max_length=100, blank=True)

    def save(self):
        super(Item, self).save()
        if self.image:
            img = Image.open(self.image.path)

            try:
                for orientation in ExifTags.TAGS.keys():
                  if ExifTags.TAGS[orientation]=='Orientation':
                      break
                exif = dict(img._getexif().items())
                if exif[orientation] == 3:
                  img=img.rotate(180, expand=True)
                  print(3)
                elif exif[orientation] == 6:
                  img=img.rotate(270, expand=True)
                  print(6)
                elif exif[orientation] == 8:
                  img=img.rotate(90, expand=True)
                  print(8)
            except (AttributeError, KeyError, IndexError):
                pass

            base_width = 550
            base = Image.new(mode='RGBA',size=(base_width,base_width),color=(255,255,255,0))
            width, height = img.size

            #SCALE IMAGE
            width_percent = (base_width/float(width))
            new_height = int((float(height)*float(width_percent)))
            img = img.resize((base_width, new_height), Image.ANTIALIAS)
            img.save(self.image.path, 'PNG')

            #CROP HORIZONTAL IMAGES MORE?
            base.paste(img, (0, int((550/2 - img.size[1]/2))))
            base.save(self.thumbnail.path, 'PNG')

list/forms.py
from django import forms
from .models import Item, List

class AddItem(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'url', 'location', 'price_range', 'description','image', 'id')

class BuyItem(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('bought',)

class AddList(forms.ModelForm):
    class Meta:
        model = List
        fields = ('name', 'description', )

list/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from .models import List, Item
from .forms import AddItem, AddList, BuyItem
from django.forms import inlineformset_factory
from django.utils.crypto import get_random_string

# TODO: add view for editing profile (firstname, lastname, email, profile picture)
# TODO: add view for creating a new list

def complete_url(url):
    return url.startswith('http')

def random_id_20():
    characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'
    return get_random_string(length=20, allowed_chars=characters)

def valid_url(url):
    if url.startswith('http'):
        return url
    return 'http://' + url

def add_item(request, id):
    list = List.objects.get(pk=id)

    if request.method == 'GET':
        form = AddItem()
        items = [(item, AddItem(instance=item)) for item in list.item_set.all()]
        form_items = [item.id for item in list.item_set.all().iterator()]
        return render(
            request,
            '../templates/items.html',
            {'form': form, 'list': list, 'items': items, 'share': False, 'form_items': form_items })

    if request.method == 'POST':
        if request.POST.get('id'):
            instance = Item.objects.get(pk=request.POST.get('id'))
            form = AddItem(request.POST, instance=instance)
        else:
            form = AddItem(request.POST)

        if form.is_valid():
            item = form.save(commit=False)
            item.list = list
            if item.url:
                item.url = valid_url(item.url)
            if 'image' in request.FILES:
                item.image = request.FILES['image']
                item.thumbnail = request.FILES['image']

            item.save()

            return HttpResponseRedirect('/lists/' + str(list.id))

def delete_item(request, list_id, item_id):
    instance = Item.objects.get(id=item_id)
    instance.delete()
    return HttpResponseRedirect('/lists/' + str(list_id))

def add_list(request):
    if request.method == 'GET':
        form = AddList()
        return render(request, '../templates/add_list.html', {'form': form})

    if request.method == 'POST':
        form = AddList(request.POST)
        if form.is_valid():
            list = form.save(commit=False)
            list.user = request.user
            list.share = random_id_20()
            list.save()
            return HttpResponseRedirect('/')

def buy(request):
    if request.method == 'POST':
        item_id = request.POST.get('item_id')
        item = Item.objects.get(pk=item_id)
        form = BuyItem(request.POST, instance=item)
        form.save()

        return HttpResponseRedirect('/' + request.POST.get('share'))

def share(request, share):
    if request.method == 'GET':
        form = BuyItem()
        list = List.objects.get(share=share)
        items = [(item, None) for item in list.item_set.all()]
        list_items = [item.id for item in list.item_set.all().iterator()]

        return render(
            request,
            '../templates/share.html',
            {'list': list, 'items': items, 'share': True, 'list_items': list_items}
        )

templates/about.html
{% extends 'base.html' %}

{% block content %}
  <div class="row">
    <div class="about center col-lg-10 col-md-10 col-sm-10 col-xs-10">
      <h2 class="padding-top-5">About</h2>
    </div>
  </div>
{% endblock %}

templates/add_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="add-list col-lg-10 col-md-10 col-sm-10 col-xs-10">
      {% if user.is_authenticated %}
        <h3>{{ list.name }}</h3>
        <div class="list-form">
          <form action="." method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input placeholder="List name" id="id_name" maxlength="100" name="name" type="text" required=""></p>
            <input placeholder="Description" id="id_description" maxlength="200" name="description" type="text"></p>
            <input id="user" name="user" type="hidden" value="{{ user }}">
            <button class="button full-width" type="submit">ADD LIST</button>
          </form>
          <div class="padding-top-1">
            <a class="cancel" href="/">
              <div class="button center">CANCEL</div>
            </a>
          </div>
        </div>
      {% else %}
        <p>Du er ikke logget inn (<a href="{% url 'login' %}">login</a>)</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Listfully{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'node_modules/flexboxgrid/dist/flexboxgrid.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/helpers.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome/css/font-awesome.min.css' %}" />

  <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}" /></script>
  <script type="text/javascript" src="{% static 'js/item.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/edit.js' %}"></script>
</head>
<body>
  <div class="container-fluid">
    <div class="header">
      {% include 'header.html' %}
    </div>
    <div class="content">
      {% block content %}
      {% endblock %}
    </div>
    <div class="footer">
      {% include 'footer.html' %}
    </div>
  </div>
</body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block content %}
  <div class="row">
    <div class="contact center col-lg-10 col-md-10 col-sm-10 col-xs-10">
      <h2 class="padding-top-5">Contact</h2>
    </div>
  </div>
{% endblock %}

templates/footer.html
<div class="row">
  <div id="diamond"></div>
  <div class="inner-diamond gotham-medium"></div>
</div>

<div class="row">
  <p class="center padding-top-3 gotham-light">LISTFULLY.</p>
</div>

templates/header.html
{% load static %}

<div class="row">
  <div class="links">
    <p>
      {% if user.is_authenticated %}
        <span>{{ user.username }}</span> (<a class="user" href="{% url 'logout' %}">logout</a>)
      {% else %}
        <a href="{% url 'login' %}">login</a>
      {% endif %}
    </p>
    {% if user.is_authenticated %}
      <p><a class="link" href="{% url 'home' %}">Lists</a></p>
    {% endif %}
    <p class="hidden"><a class="link" href="{% url 'contact' %}">Contact</a></p>
    <p class="hidden"><a class="link" href="{% url 'about' %}">About</a></p>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12	col-lg-12">
    <div class="logo center">
      <a href="/">
        <img src="{% static 'images/listfully.png' %}"></img>
      </a>
    </div>
    <hr class="logo-underline" />
  </div>
</div>

templates/home.html
{% extends 'base.html' %}

{% block content %}
  <div class="home">
    {% if user.is_authenticated %}
      <div class="center">
        {% include 'lists.html' %}
      </div>
    {% else %}
      <div class="row">
        <div class="introduction center padding-bottom-1">
          <p>
            Gifts cause stress. Giving shouldn’t.
            Listfully is a space where you can <bold class="gotham-medium">create personalized lists</bold>
            of anything you’d like to receive as a gift, and <bold class="gotham-medium">share your list</bold> with family
            and friends
          </p>

          <p class="padding-top-2 padding-bottom-2">
            Unlike other gift registries, Listfully provides total freedom to
            <bold class="gotham-medium">list anything</bold> from anywhere, both online and in the physical world.
            Using Listfully saves time and avoids uncertainty in finding the right gift.
          </p>

          <p class="no-mobile padding-top-1 padding-bottom-1">
            But the very best thing about Listfully is that you can use it to
            do good. Support small businesses by listing locally. Be mindful in
            choosing gifts that can be sustainable, experience-based, consumable,
            or charitable. Your lists are your space, and anything you want them
            to be.
          </p>

          <p class="garamond padding-top-2">
            So list consciously. List creatively. List freely.
          </p>

          <p class="garamond padding-bottom-5">
            List fully.
          </p>
        </div>
      </div>

      <div class="row">
        <div class="home-buttons center">
          <div class="button start">
            <a class="" href="{% url 'login' %}">LOG IN</a>
          </div>
          <div class="button start">
            <a class="" href="/register">REGISTER</a>
          </div>
        </div>
      </div>
    {% endif %}
  </div>
{% endblock %}

templates/information.html
{% load static %}

{% block content %}
  <p>
    Velkommen til siden vår :) På denne siden kan du lage din egen ønskeliste!
    Nedenfor ligger en fin liste med ikoner du kan se på frem til det kommer
    noe spennende du kan gjøre.
  </p>
  <div class="row">
    <img class="icon-xs" src="{% static "images/calendar.svg" %}" alt="something" >
    <img class="icon-small" src="{% static "images/calendar.svg" %}" alt="something" >
    <img class="icon-medium" src="{% static "images/calendar.svg" %}" alt="something" >
    <img class="icon-large" src="{% static "images/calendar.svg" %}" alt="something" >
    <img class="icon-xl" src="{% static "images/calendar.svg" %}" alt="something" >
  </div>

  <div class="row">
    <img class="icon-xs" src="{% static "images/gift.svg" %}" alt="something" >
    <img class="icon-small" src="{% static "images/gift.svg" %}" alt="something" >
    <img class="icon-medium" src="{% static "images/gift.svg" %}" alt="something" >
    <img class="icon-large" src="{% static "images/gift.svg" %}" alt="something" >
    <img class="icon-xl" src="{% static "images/gift.svg" %}" alt="something" >
  </div>

  <div class="row">
    <img class="icon-xs" src="{% static "images/diamond-pink.svg" %}" alt="something" >
    <img class="icon-small" src="{% static "images/diamond-pink.svg" %}" alt="something" >
    <img class="icon-medium" src="{% static "images/diamond-pink.svg" %}" alt="something" >
    <img class="icon-large" src="{% static "images/diamond-pink.svg" %}" alt="something" >
    <img class="icon-xl" src="{% static "images/diamond-pink.svg" %}" alt="something" >
  </div>

  <div class="row">
    <img class="icon-xs" src="{% static "images/paper-plane.svg" %}" alt="something" >
    <img class="icon-small" src="{% static "images/paper-plane.svg" %}" alt="something" >
    <img class="icon-medium" src="{% static "images/paper-plane.svg" %}" alt="something" >
    <img class="icon-large" src="{% static "images/paper-plane.svg" %}" alt="something" >
    <img class="icon-xl" src="{% static "images/paper-plane.svg" %}" alt="something" >
  </div>
{% endblock %}

templates/item_list.html
<div class="row item-container">
  {% for item, form in items %}
    <div class="item col-lg-4 col-md-6 col-sm-6 col-xs-12">
      {% if item.image %}
        <img class="item-image" src="{{MEDIA_URL}}{{ item.thumbnail }}" alt="" />
      {% else %}
        <div class="item-image beige"></div>
      {% endif %}

      <div class="item-info" id="item-info-{{ item.id }}">
        <h4 class="name">{{ item.name }}</h4>
        <div class="item-links">
          {% if item.url %}
            <p>
              <i class="fa fa-link"></i>
              <a class="url" target="_blank" href="{{ item.url }}">{{item.url}}</a>
            </p>
          {% endif %}
          {% if item.location %}
            <p>
              <i class="fa fa-map-marker"></i>
              <a class="location" target="_blank" href="http://maps.google.com/?q={{ item.location }}">
                {{ item.location }}
              </a>
            </p>
          {% endif %}
        </div>
        {% if item.price_range %}
          <p class="price_range"><b class="gotham-medium">Price:</b> {{ item.price_range }}</p>
        {% endif %}
        {% if item.description %}
          <p class="description"><b class="gotham-medium">Description:</b> {{ item.description }}</p>
        {% endif %}

        {% if share %}
          <div class="buy-form">
            <form action="/lists/buy/" method="POST">
              {% csrf_token %}
              <input name="bought" class="hidden" value="{{ item.bought|yesno:'False,True' }}" />
              <input id="bought-{{ item.id }}"  type="button" class="button" value="{{ item.bought|yesno:'-- RESERVED --, RESERVE TO BUY' }}" />
              <input id="item_id" name="item_id" type="hidden" value="{{ item.id }}" />
              <input id="share" name="share" type="hidden" value="{{ list.share }}" />
              <input id="buy-item-{{ item.id }}" type="Submit" value="Submit" class="hidden" />
            </form>
          </div>
        {% else %}
          <a class="delete" href='delete/{{item.id}}/'>
            <i class="fa fa-trash" aria-hidden="true"></i>
          </a>
          <a id="edit-item-{{ item.id }}" href="javascript:void(0)">
            <i class="fa fa-pencil edit" aria-hidden="true"></i>
          </a>
        {% endif %}
      </div>

      {% if user.is_authenticated and not share %}
        <div id="edit-form-{{ item.id }}" hidden="">
          <form action="." method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input value="{{ item.name }}" id="id_name" placeholder="Name" maxlength="50" name="name" type="text" required="">
            <input value="{{ item.url }}" id="id_url" placeholder="Url" maxlength="500" name="url" type="text">
            <input value="{{ item.location }}" id="id_location" placeholder="Location" maxlength="100" name="location" type="text">
            <input value="{{ item.price_range }}" id="id_price_range" placeholder="Price" maxlength="20" name="price_range" type="text">
            <input value="{{ item.description }}" id="id_description" placeholder="Details" maxlength="100" name="description" type="text">
            <input class="padding-top-2 padding-bottom-2" id="id_image" name="image" type="file">
            <input value="{{ item.id }}" id="id_id" name="id" type="hidden">
            <input value="{{ user }}" id="user" name="user" type="hidden">
            <button class="button full-width" type="submit">SAVE CHANGES</button>
          </form>
          <button id="cancel-item-{{ item.id }}" class="button full-width">CANCEL</button>
        </div>
      {% endif %}
    </div>
  {% endfor %}
</div>

{% if user.is_authenticated %}
  <script type="text/javascript">
    $( document ).ready(function() {
      edit.bindForm({{ form_items }});
    });
  </script>
{% endif %}

templates/items.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  {% if user.is_authenticated %}
    <div class="row">
      <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10 list-title center">
        <h2 class="garamond list-name">{{ list.name }}</h2>
        <p class="list-link">
          <p class="bold">
            <i class="fa fa-link" aria-hidden="true"></i>
            Share:
            <a class="share" target="_blank" href="http://{{ request.get_host }}/{{ list.share }}">
               {{ request.get_host }}/{{ list.share }}
            </a>
          </p>
        </p>
      </div>
      <div class="col-lg-4 col-md-8 col-sm-9 col-xs-10 list-form center">
        <form action="." method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <input id="id_name" placeholder="Name – what do you want to add?" maxlength="50" name="name" type="text" required="">
          <input id="id_url" placeholder="Link - can they find it online?" maxlength="500" name="url" type="text">
          <input id="id_location" placeholder="Location – can they find it somewhere?" maxlength="100" name="location" type="text">
          <input id="id_price_range" placeholder="Price – what does it cost? (approximate) " maxlength="20" name="price_range" type="text">
          <input id="id_description" placeholder="Comment - i.e brand, color and size" maxlength="100" name="description" type="text">
          <input class="padding-top-2 padding-bottom-2" id="id_image" name="image" type="file">
          <input id="user" name="user" type="hidden" value="{{ user }}">
          <button class="button full-width" type="submit">ADD ITEM</button>
        </form>
        <input class="product url input" placeholder="Product URL" type="text" >
        <button class="product url submit button full-width">GET ITEM INFO FROM LINK</button>
      </div>
    </div>
    {% include 'item_list.html' %}
  {% else %}
    <p>Du er ikke logget inn (<a href="{% url 'login' %}">login</a>)</p>
  {% endif %}
  <script>
      $('.product.url.submit').click(function() {
          var url = $('.product.url.input').val();
          $.get({
              url: 'http://api.diffbot.com/v3/product',
              data: {
                  url: url,
                  token: 'f09ac558911c7ae07146caae219dfb4a',
                  fields: 'pageUrl,title,regularPrice,images'
              },
              dataType: 'json'
          }).then(function(response) {
              if (response.objects.length < 1) {
                  alert('Could not find any product information');
                  return;
              }
              var product = response.objects[0];
              $('#id_name').val(product.title);
              $('#id_url').val(product.pageUrl);
              $('#id_price_range').val(product.regularPrice);
          });
      });
  </script>
{% endblock %}

templates/lists.html
<div class="row">
  <div class="lists col-lg-7 col-md-7 col-sm-10 col-xs-10">
    {% if user.is_authenticated %}
      {% if not user.list_set.all %}
        <div class="row padding-top-5">
          <p class="center">You don't have any lists yet. Create one?</p>
        </div>
        <div class="row padding-top-10">
          <a class="create-list button center" href="{% url 'add_list' %}">CREATE YOUR FIRST LIST</a>
        </div>
      {% else %}
        {% for list in user.list_set.all %}
          <a class="list" href="/lists/{{ list.id }}">
            <div class="list-item">
              <div class="list-box">
                <p class="item-list-name">{{ list.name }}</p>
              </div>
            </div>
          </a>
        {% endfor %}
        <div class="padding-top-2 padding-bottom-10">
          <a class="create-list button" href="{% url 'add_list' %}">
            <i class="fa fa-plus" aria-hidden="true"></i>
            CREATE NEW LIST
          </a>
        </div>
      {% endif %}
    {% else %}
      <p>Du er ikke logget inn (<a href="{% url 'login' %}">login</a>)</p>
    {% endif %}
  </div>
</div>

templates/profile.html
{% extends 'base.html' %}

{% block content %}
  <div class="row">
    <div class="profile center col-lg-10 col-md-10 col-sm-10 col-xs-10">
      {% if user.is_authenticated %}
        <h2 class="padding-top-2 padding-bottom-2">Hi, {{ user.username }}!</h2>
        {% include 'lists.html' %}
      {% else %}
        <p>You are not logged in (<a href="{% url 'login' %}">login</a>)</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/share.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10 list-title center">
      <h2 class="garamond list-name">{{ list.user }}'s list <span class="underline">{{ list.name }}</span>:</h2>
    </div>
  </div>

  {% include 'item_list.html' %}

  <script type="text/javascript">
    $( document ).ready(function() {
      items.bindForm({{ list_items }});
    });
  </script>
{% endblock %}